image: technic93/e2xvfb:0.1

before_script:
  - uname -a
  - whoami

pep8:
  image: python:2.7.15
  script:
    - pip install pep8
    - pep8 --ignore E126,E266,E226,W191,W293,E731 --max-line-length=119 src

shellcheck:
  image:
    name: koalaman/shellcheck-alpine
  script:
    - find -name '*.sh' -print |xargs -n 1 shellcheck
  allow_failure: true

.test:
  script: &test_script
    - ps ax
    - export PROVIDER=WowTV
    - sudo -E python update-test.py

test:wow:
  variables:
    PROVIDER: WowTv
  only:
    - wow
  script: *test_script

test:cbilling:
  variables:
    PROVIDER: cbilling
  only:
    - cbilling
  script: *test_script

.deploy:
  image: python:2.7.15
  stage: deploy
  when: manual
  script:
    # GitLab ssh setup
    - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    # End of ssh setup
    - apt-get update && apt-get install -y gettext lftp rsync
    - echo $PROVIDER
    - make
    - make DEB=y
    - rsync -rt --delay-updates packages/ $UPDATE_SERVER:~/iptvdream4x/packages

deploy:wow:
  extends: .deploy
  only:
    - wow
  variables:
    PROVIDER: WowTV

deploy:cbilling:
  extends: .deploy
  only:
    - cbilling
  variables:
    PROVIDER: cbilling
