image:
  name: technic93/e2xvfb:0.1
  run-as-user: 0

stepdefs:
  - testing: &testing
      name: Run tests
      caches:
        - pip
      script:
        - uname -a
        - whoami
        - mkdir -p /dev/input
        - service apache2 start
        - Xvfb :99 -ac -screen 0 1280x720x16 &
        - export DISPLAY=:99
        - ps ax
        - pip install pycodestyle
        - pycodestyle --version
        - pycodestyle src
        - python update-test.py

pipelines:
  custom:
    test:
      - step: *testing
  tags:
    v/*:
      - step: *testing
      - step:
          name: Deploy packages
          image: python:2.7.15
          deployment: staging
          script:
            - apt-get update && apt-get install -y gettext rsync
            - pip install requests
            - make
            - make DEB=y
            - rsync -rt --delay-updates packages/ $UPDATE_SERVER:~/iptvdream4x/packages
            - export API_URL="https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads"
            - curl -X POST -u "${BB_AUTH_STRING}" "${API_URL}" -F files=@"$(find packages/ -type f -name '*.ipk')"
            - curl -X POST -u "${BB_AUTH_STRING}" "${API_URL}" -F files=@"$(find packages/ -type f -name '*.deb')"
            - python ./scripts/telegram-bot.py
