version: "2"
services:
  enigma2:
    image: e2full
    build:
      context: vm-docker
    container_name: enigma2
    working_dir: /project
    ports:
      - 5900:5900
      - 5678:5678
    volumes:
      - "./src:/usr/lib/enigma2/python/Plugins/Extensions/IPtvDream"
      - "./skin:/usr/share/enigma2/IPtvDream"
      - "./skin-fhd:/usr/share/enigma2/IPtvDreamFHD"
      - "./skin-fhd-contrast:/usr/share/enigma2/IPtvDreamFHDContrast"
      - "./:/project"
    environment:
      - RESOLUTION=1920x1080x16
